name: fstore
publish_to: "none"
description: Mobile commerce app by Flutter

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.1.0+21
environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  animated_text_kit: 4.2.2
  animations: 2.0.7
  cached_network_image: 3.2.3
  carousel_slider: ^4.2.1
  cloud_firestore: 4.7.1
  country_code_picker: 3.0.0
  country_pickers: 2.0.0
  crypto: 3.0.3
  cupertino_icons: 1.0.5
  devicelocale: 0.6.0
  dotted_decoration: 2.0.0
  dropdown_search: 5.0.6
  easy_debounce: 2.0.3
  echart_flutter: ^0.1.0+2
  email_validator: 2.1.17
  extended_image: 8.0.1
  file_picker: 5.3.1
  firebase_analytics: 10.4.1
  firebase_auth: 4.6.1
  firebase_core: 2.13.0
  firebase_dynamic_links: 5.3.1
  firebase_messaging: 14.6.1
  firebase_remote_config: 4.2.1
  flare_loading: 3.0.0
  flash: 2.0.5+1
  flex_color_scheme: 7.1.2
  flutter:
    sdk: flutter
  flutter_cache_manager: 3.3.0
  flutter_calendar_carousel: 2.4.2
  flutter_inappwebview: ^5.5.0
  flutter_linkify: 6.0.0
  flutter_local_notifications: 14.1.0
  flutter_localizations:
    sdk: flutter
  flutter_native_image: 0.0.6+1
  flutter_native_splash: 2.3.0
  flutter_spinkit: 5.2.0
  flutter_staggered_grid_view: 0.6.2
  flutter_svg: 2.0.6
  flutter_swiper_null_safety: 1.0.2
  flutter_widget_from_html_core: 0.10.1
  flutter_zoom_drawer: 3.0.4+1
  fwfh_cached_network_image: 0.7.0+5
  fwfh_svg: 0.8.0+2
  fwfh_url_launcher: 0.9.0+2
  fwfh_webview: 0.7.0+2
  get_it: 7.6.0
  gms_check: 1.0.1
  google_fonts: 4.0.4
  google_sign_in: 6.1.2
  html: ^0.15.4
  html_unescape: 2.0.0
  http: 0.13.6
  http_auth: 1.0.1
  image: 4.0.17
  image_picker: 0.8.7+5
  inspireui: ^1.5.0
  intl: ^0.18.0
  intro_slider: 4.2.0
  json_annotation: 4.8.1
  localstorage: 4.0.1+2
  lottie: 2.3.2
  maps_launcher: 2.2.0
  path_provider: 2.0.15
  paytm_allinonesdk: 1.2.1
  pin_code_fields: 7.4.0
  provider: 6.0.5
  pull_to_refresh: 2.0.0
  qr_code_scanner: 1.0.1
  random_string: 2.3.1
  rate_my_app: 2.0.0
  responsive_builder:
    git:
      url: https://github.com/FilledStacks/responsive_builder
      ref: 876876d6977b9327db0b3bb906747a02bb64b790
  rive: 0.11.1
  share: 2.0.4
  shared_preferences: ^2.1.1
  smooth_page_indicator: 1.1.0
  sms_autofill: 2.3.0
  the_apple_sign_in: 1.1.1
  timeago: 3.4.0
  transparent_image: 2.0.1
  universal_platform: 1.0.0+1
  url_launcher: 6.1.11
  uuid: 3.0.7
  video_player: 2.6.1
  visibility_detector: 0.3.3
  webview_flutter: 4.2.1
  webview_flutter_web: 0.2.2+1
  xml: ^6.3.0
  xml2json: ^6.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: 2.0.1
#  convert_data:
#    path: _dev/convert_data
## Enable to use Flutter Test Driver
#  flutter_driver:
#    sdk: flutter
#  test: 1.16.5
#  dependency_validator: ^3.1.2  # pub run dependency_validator
## Enable To run json serializer, run:
## flutter pub run build_runner build --build-filter="lib/models/serializers/*.dart" --delete-conflicting-outputs
## flutter pub run build_runner serve --build-filter="lib/models/serializers/*.dart"
#  build_runner: 2.0.3
#  json_serializable: 4.1.2
#  Run this script to generate the app icon: flutter pub run flutter_launcher_icons:main
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon_ios.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - lib/config/
    - lib/config/mocks/
    - lib/config/states/
    - lib/config/stories/
    - assets/icons/credit_cards/
    - assets/icons/tabs/
    - assets/icons/payment/
    - assets/icons/logins/
    - assets/images/
    - assets/images/country/
    - assets/images/favicon/
    - assets/html/
    - google_fonts/

  fonts:
    - family: PFCentury Regular
      fonts:
        - asset: google_fonts/PFCentury-Regular.ttf
    - family: PFCentury Bold
      fonts:
        - asset: google_fonts/PFCentury-Bold.ttf
    - family: PFCentury Bold Italic
      fonts:
        - asset: google_fonts/PFCentury-BoldItalic.ttf
    - family: PFCentury Italic
      fonts:
        - asset: google_fonts/PFCentury-Italic.ttf
    - family: PFCentury Medium Italic
      fonts:
        - asset: google_fonts/PFCenturyMedium-Italic.ttf
    - family: PFCentury Medium Regular
      fonts:
        - asset: google_fonts/PFCentury-Italic.ttf

flutter_intl:
  enabled: true
  use_deferred_loading: true
